# Generated by Django 4.2.20 on 2025-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('BALLET_FLAT', 'Ballet Flat'), ('SNEAKER', 'Sneaker'), ('BOOT', 'Boot'), ('SANDAL', 'Sandal')], max_length=50, null=True),
        ),
    ]
